Version one
RoyNyaga/using_bootstrap pull request #1
Opened 2019-08-06 02:19 UTC by RoyNyaga

There are some comments i left in my html and css files, it's for the purpose of easy review. Will clean that up when the project is accepted.

2019-08-06 04:42 UTC, Ispirett commented
Hey, @RoyNyaga  great work with this project you did a  fantastic job :1st_place_medal: Also love your read me file :+1: .  Just some minor fixes 

### HTML errors
There are a  few  HTML errors on this page use this tool and please correct them https://validator.w3.org/.

### Optional changes
Using `<section>` tags instead of `<div>` for groups of related articles is good practice.

2019-08-06 23:42 UTC, RoyNyaga commented
I rectified all the errors thrown by the markup validator and implemented section tags for main sections in the main tag. I also added the last section of the main tag as requested. I purposely left comments in my work for easy review in case there are any.

2019-08-07 00:35 UTC, bolah2009 commented
Currently under review

2019-08-07 00:47 UTC, bolah2009 requested changes
## Awesome Job [Roy](../../) :clap: 

Awesome job so far, the [clone](https://raw.githack.com/RoyNyaga/using_bootstrap/version_one/index.html) looks good to me and very responsive.. :clap:

However, use more of bootstrap as pointed out in [this comment](https://github.com/RoyNyaga/using_bootstrap/pull/1#discussion_r311328999) and all other occurrences and make the navbar fixed as in the [original site](https://www.newsweek.com/), this is to make the homepage and website menu accessibility anyway in the page especially for long websites which is the case in this website. See below for illustration:

|Current|Preffered|
| :-----: | :------: |
| ![newsweek fix navbar cureent](https://user-images.githubusercontent.com/36057474/62586315-f2e18200-b8b4-11e9-82c5-7e631e42e93e.gif) | ![newsweek fix navbar preffred](https://user-images.githubusercontent.com/36057474/62586327-fbd25380-b8b4-11e9-92bd-7247ab96a9ca.gif) |

Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-08-07 00:47 UTC, bolah2009 commented on css/style.css
> +  position: absolute;
`SUGGESTION`

Consider using a bootstrap class instead. _Note that the project is about using bootstrap._

2019-08-07 00:47 UTC, bolah2009 commented on css/style.css
> +  position: relative;
`SUGGESTION`

Consider using a bootstrap class instead. _Note that the project is about using bootstrap._

2019-08-07 00:47 UTC, bolah2009 commented on css/style.css
> +  display: inline-block;
`SUGGESTION`

Consider using a bootstrap class instead. _Note that the project is about using bootstrap._

2019-08-07 16:38 UTC, RoyNyaga commented
Added the bootstrap navbar-fixed to create a fixed nav and added more bootstrap classes as demanded. Notice in some areas i couldn't use the bootstrap margin and padding because the highest it could produce (ie m-5) was not enough to produce the effect i wanted.

2019-08-07 19:23 UTC, samgaco commented
### Hi @RoyNyaga :hand: 

### Good work implementing the changes required in the previous reviews. Congratulations because your project is approved :+1: :tada: 

**[OPTIONAL]** _There are some things that you could still improve like the icons at the footer (they should arrange below the logo in the smaller screen size, or the opinion section in the medium screen size get's too much empty space at its right. Those would be things to work on if you would like to keep digging into this project._

### You may merge to the master branch and submit the project completion form. Keep the good work for the next projects :muscle: Regards!.

2019-08-07 20:31 UTC, RoyNyaga commented
Ok thanks for the quick review, i will try and improve the icons at the
footer for smaller screens before submitting.

On Wed, Aug 7, 2019 at 8:23 PM samgaco <notifications@github.com> wrote:

> Hi @RoyNyaga <https://github.com/RoyNyaga> ✋ Good work implementing the
> changes required in the previous reviews. Congratulations because your
> project is approved 👍 🎉
>
> *[OPTIONAL]* *There are some things that you could still improve like the
> icons at the footer (they should arrange below the logo in the smaller
> screen size, or the opinion section in the medium screen size get's too
> much empty space at its right. Those would be things to work on if you
> would like to keep digging into this project.*
> You may merge to the master branch and submit the project completion form.
> Keep the good work for the next projects 💪 Regards!.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/RoyNyaga/using_bootstrap/pull/1?email_source=notifications&email_token=ALZGFHNWLFQR4ALVJAQ6EO3QDMOJNA5CNFSM4IJRLJUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3ZONSI#issuecomment-519235273>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALZGFHINQEQQP43NGJ36WXDQDMOJNANCNFSM4IJRLJUA>
> .
>

2019-08-12 02:48 UTC, merged